version: '3.8'

services:
  redis:
    image: focker.ir/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  postgres:
    image: focker.ir/postgres
    container_name: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
